# +-------+
# | 1 | 3 |
# +---+   |
# | 2 |   |
# +-------+

split-window -h
select-pane -t 1
split-window -v
#send-keys "make tailwind" Enter
select-pane -t 1
send-keys "make eleventy" Enter
select-pane -t 3
send-keys "xdg-open http://localhost:8080 || open http://localhost:8080" Enter
send-keys "clear" Enter

